package Tela;

import javax.swing.JOptionPane;

/**
 * @Author Jorgi Bolonhezi
 * @IDE Apache Netbeans 12.3 & Eclipse Luna
 */

public class Painel extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemEsconderTexto = new javax.swing.JMenuItem();
        jMenuItemExtrairTexto = new javax.swing.JMenuItem();
        jMenuItemCréditos = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho de Criptografia - INFO7010");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("   ------------------------------ Trabalho de Criptografia - Esteganografia ------------------------------\n\n   Esteganografia consiste em esconder um texto dentro de outro texto ou dentro de uma imagem.\n   É diferente da criptografia. Na criptografia qualquer pessoa pode ter acesso ao texto cifrado,\n   mas não deve conseguir decifrar o texto. Já na esteganografia o texto claro esta somente escondido\n   dentro de outro texto ou de uma imagem, o texto claro continua \"aberto\". Na era da computação, a\n   forma tradicional de estaganografia é esconder um texto dentro de um arquivo de imagem ou de audio. \n   A ideia deste trabalho é voces procurarem formas de esteganografia na computação, escolher uma\n   destas formas e implementar. Podem usar qualquer linguagem de programação.\n   Voces devem analisar o arquivo original e o arquivo modificado, mostrando as diferenteças\n   de tamanho do arquivo e outras caracteristicas que foram alteradas na esteganografia.\n   Trabalho individual. Os trabalho serão apresentados na quinta (18/03) e sexta (19/03).\n\n   Disciplina: CRIPTOGRAFIA - INFO7010 - Período Especial II\n   Docente: Luiz Carlos Pessoa Albini\n   Discente: Jorgi Luiz Bolonhezi Dias\n\n   NOTA: ESTEGANOGRAFIA EM IMAGENS BMP\n   UTILIZAR CARACTERES DO FORMATO UTF8 LISTADOS ABAIXO\n\n   abcdefghijklmnopqrstuvwxyzŕâéčęëîďôůűü˙çABCDEFGHIJKLMNOPQRSTUVWXYZŔÂČÉĘËÎĎÔŮŰÜÇ\n   0123456789,.;:!?'Ťť\\\"()+-*/=<>[]{}|%\"&~#@\\\\^\\t\\n\\r§\n");
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("Opções");

        jMenuItemEsconderTexto.setText("Esconder Texto");
        jMenuItemEsconderTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEsconderTextoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEsconderTexto);

        jMenuItemExtrairTexto.setText("Extrair Texto");
        jMenuItemExtrairTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtrairTextoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExtrairTexto);

        jMenuItemCréditos.setText("Créditos");
        jMenuItemCréditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCréditosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCréditos);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItemEsconderTextoActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        Esconder_Texto Esconder = new Esconder_Texto();
        Esconder.setLocationRelativeTo(null);
        Esconder.setVisible(true);
    }                                                      

    private void jMenuItemExtrairTextoActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        Extrair_Texto Extrair = new Extrair_Texto();
        Extrair.setLocationRelativeTo(null);
        Extrair.setVisible(true);
    }                                                     

    private void jMenuItemCréditosActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        JOptionPane.showMessageDialog(null, "Programa desenvolvido por Jorgi Bolonhezi para a Disciplina de Criptografia do Programa de Pós-Graduação em Informática da Universidade Federal do Paraná.");
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Painel Painel_Inicial = new Painel();
            Painel_Inicial.setLocationRelativeTo(null);//Inicia o painel no centro da tela
            Painel_Inicial.setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCréditos;
    private javax.swing.JMenuItem jMenuItemEsconderTexto;
    private javax.swing.JMenuItem jMenuItemExtrairTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration                   
}
